### ISSUE TITLE
Jellyfin 10.4.1 breaks this plugin

### ISSUE THREAD

**Issue by fhriley** [jellyfin/jellyfin-kodi#136]
**Describe the bug**

Jellyfin released 10.4.1 yesterday, and now the jellyfin plugin 0.3.5 running on an Nvidia Shield will not connect to the server. I have reproduced this on both of my Shield kodi frontends.
 
**To Reproduce**

Run Jellyfin server 10.4.1 on Linux.
Try to connect with this plugin.

**Expected behavior**

Connects properly.

**Logs**

```
2019-11-04 18:51:22.535 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:278 tryConnect url: http://jellyfin:8096/emby/system/info/public
2019-11-04 18:51:22.536 T:9278  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 22688 m_frames: 1418 m_frameSize: 8 channels: 2
2019-11-04 18:51:22.570 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:151 connectToAddress http://jellyfin:8096 succeeded
2019-11-04 18:51:22.571 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:165 begin connectToServer
2019-11-04 18:51:22.573 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:179 beginning connection tests
2019-11-04 18:51:22.574 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:301 testing connection mode 2 with server None
2019-11-04 18:51:22.574 T:9379  NOTICE: JELLYFIN.jellyfin.core.connection_manager -> INFO::resources/lib/jellyfin/core/connection_manager.py:278 tryConnect url: http://jellyfin:8096/emby/system/info/public
2019-11-04 18:51:22.683 T:9379   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/servermanual.py", line 83, in onClick
                                                elif self._connect_to_server(server):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/servermanual.py", line 120, in _connect_to_server
                                                result = self.connect_manager.connect_to_address(server)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/jellyfin/core/connection_manager.py", line 157, in connect_to_address
                                                server = self.connect_to_server(server, options)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/jellyfin/core/connection_manager.py", line 180, in connect_to_server
                                                return self._test_next_connection_mode(tests, 0, server, options)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/jellyfin/core/connection_manager.py", line 332, in _test_next_connection_mode
                                                if self._compare_versions(self._get_min_server_version(), result['Version']) == 1:
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
```
**System (please complete the following information):**
 - OS: AndroidTV (Nvidia Shield)
 - Jellyfin Version: 10.4.1
 - Kodi Version: 18.4
 - Addon Version: 0.3.5

**Additional context**
Reverting the server back to 10.4.0 allows the plugin to connect properly.

**Comment by mcarlton00** [comment]
The addon itself works fine on 10.4.1, but there is the potential for breakage in the process of the update.  This is almost certainly related to the baseurl change in 10.4.1 server.  Details about this are outlined in the [release notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1).  If this is the case, then your options are to either reset the kodi database and do a fresh sync, or revert the baseurl to what it was previously.

To reset the kodi data, go to `Add-ons -> Jellyfin -> Perform local database reset`.  When it asks you to clear jellyfin settings, do so and start fresh
